# grafana/provisioning/datasources/questdb.yml
apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    url: questdb:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true
